### PR TITLE
docs: code of conduct

### PR DESCRIPTION
**Pull request by Soham041201**
Changed the radius of the photo

### CODE REVIEW

**Comment by eddiejaoude** [comment]
Thank you, I used the Avatar component that has circle in Prime React https://www.primefaces.org/primereact/showcase/#/avatar

Btw the PR title does not match the changes

**Review by stemount — COMMENTED** [review]
@Soham041201 you should configure your IDE to add a space after a file (at end of line). in `image.css` it actually shows you a 🚫 because of a lack of space after end of file

**Comment by Soham041201** [comment]
> @Soham041201 you should configure your IDE to add a space after a file (at end of line). in `image.css` it actually shows you a  because of a lack of space after end of file

Cool! will change ASAP

**Comment by stemount** [comment]
@Soham041201 just in case it's lost: https://link.ste.london/vscode-new-line-EOL

**Pull request closed without merging**
